---
- hosts: all
  vars:
    nginx_port: 9090
    root_dir: /usr/share/nginx/html
  become: true
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: true
    - name: copy nginx config
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
    - name: html page
      ansible.builtin.copy:
        src: files/index.html
        dest: "{{ root_dir }}/index.html"
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
