- hosts: other
  tasks:
  - name: Configure DNS
    ansible.builtin.copy:
      dest: /etc/resolv.conf
      content: |
        nameserver 8.8.8.8
        nameserver 1.1.1.1
      owner: root
      group: root
      mode: '0644'
    become: True
  
  - name: Install Git
    ansible.builtin.apt:
      name: git
      state: present
      update_cache: yes
    become: True

